### ISSUE TITLE
Python environment problem -- the version of xarray?

### ISSUE THREAD

**Issue by OuyangWenyu** [cheginit/pydaymet#9]
**What happened**: 
When installing the conda environment with "xarray", the default version is xarray-0.18.0. However, this caused an error in both Ubuntu and Windows as follows when performing: "monthly = daymet.get_bygeom(geometry, dates, variables=var, time_scale="monthly")" in the sample code in README.md (same error for "daily = daymet.get_bygeom(geometry, dates, variables=var, pet=True)" ). But after I fixed the version of xarray to 0.16, it worked. I am not sure whether it is a bug in xarray or in pydaymet.

```Python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\11445\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\211.7142.13\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Users\11445\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\211.7142.13\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/Code/HydroBench/src/daymet.py", line 15, in <module>
    monthly = daymet.get_bygeom(geometry, dates, variables=var, time_scale="monthly")
  File "C:\Users\11445\miniconda3\envs\hydro-bench-err\lib\site-packages\pydaymet\pydaymet.py", line 569, in get_bygeom
    clm = xr.open_mfdataset(ogc.async_requests(urls, "binary", max_workers=8))
  File "C:\Users\11445\miniconda3\envs\hydro-bench-err\lib\site-packages\xarray\backends\api.py", line 918, in open_mfdataset
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "C:\Users\11445\miniconda3\envs\hydro-bench-err\lib\site-packages\xarray\backends\api.py", line 918, in <listcomp>
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "C:\Users\11445\miniconda3\envs\hydro-bench-err\lib\site-packages\xarray\backends\api.py", line 507, in open_dataset
    ds = _dataset_from_backend_dataset(
  File "C:\Users\11445\miniconda3\envs\hydro-bench-err\lib\site-packages\xarray\backends\api.py", line 322, in _dataset_from_backend_dataset
    ds = _chunk_ds(
  File "C:\Users\11445\miniconda3\envs\hydro-bench-err\lib\site-packages\xarray\backends\api.py", line 283, in _chunk_ds
    mtime = _get_mtime(filename_or_obj)
  File "C:\Users\11445\miniconda3\envs\hydro-bench-err\lib\site-packages\xarray\backends\api.py", line 199, in _get_mtime
    if path and not is_remote_uri(path):
  File "C:\Users\11445\miniconda3\envs\hydro-bench-err\lib\site-packages\xarray\core\utils.py", line 652, in is_remote_uri
    return bool(re.search(r"^[a-z][a-z0-9]*(\://|\:\:)", path))
  File "C:\Users\11445\miniconda3\envs\hydro-bench-err\lib\re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
```
**Minimal Complete Verifiable Example**:

I just used the example code
```python
# Put your MCVE code here
import matplotlib.pyplot as plt
import pydaymet as daymet
from pynhd import NLDI

geometry = NLDI().get_basins("01031500").geometry[0]
var = ["prcp", "tmin"]
dates = ("2000-01-01", "2000-03-31")
# daily = daymet.get_bygeom(geometry, dates, variables=var, pet=True)
monthly = daymet.get_bygeom(geometry, dates, variables=var, time_scale="monthly")
ax = monthly.prcp.plot(x="x", y="y", row="time", col_wrap=3)
plt.show()
```

**Anything else we need to know?**:

The conda environment.yml files I used:

Environment with error (when replace "xarray" with "xarray-0.16.2", it worked):

```yaml
name: xxx
channels:
  - conda-forge
  - defaults
dependencies:
  - aiodns
  - aiohttp
  - brotlipy
  - chardet
  - cytoolz
  - defusedxml
  - nest-asyncio
  - orjson
  - owslib
  - pyproj
  - requests
  - setuptools
  - shapely
  - simplejson
  - pygeoogc=0.10.1
  - geopandas
  - netcdf4
  - rasterio
  - xarray
  - pygeoutils=0.10.1
  - networkx
  - pyarrow
  - pynhd=0.10.1
  - folium
  - lxml
  - matplotlib
  - openpyxl
  - py3dep=0.10.1
  - dask
  - scipy
  - pygeohydro=0.10.1
  - pydaymet=0.10.1
```

**Comment by cheginit** [comment]
Thanks for bringing this to my attention. It seems that `xarray.open_mfdataset` has changed its previous behavior and don't accept byte-like objects. It's an easy fix, I'll push a fix soon.

**Comment by OuyangWenyu** [comment]
Great! Thanks.

**Comment by cheginit** [comment]
The problem should be solved now. You can give this a try by installing `pydaymet` from github until I release a new version officially. You can do so like this:

```bash
pip install \
git+https://github.com/cheginit/pydaymet.git \
git+https://github.com/cheginit/async_retriever.git \
git+https://github.com/cheginit/pygeoogc.git \
git+https://github.com/cheginit/pygeoutils.git
```

**Comment by OuyangWenyu** [comment]
Thank you! I have installed it successfully. 

I think it would be better to close this issue after you release the new version officially so that others could notice it.

**Comment by cheginit** [comment]
Sure, thanks!

**Comment by cheginit** [comment]
I just released a new version that includes this fix among other things.

**Comment by OuyangWenyu** [comment]
Great! Thanks!
